---
- name: Ensure latest git is installed
  apt: pkg=git state=latest

- name: Ensure Discourse directory exists
  file: path={{ discourse_root }} owner=deploy group=deploy state=directory
- name: Clone Discourse docker image
  git:
    repo: https://github.com/discourse/discourse_docker.git
    dest: "{{ discourse_root }}"
- name: Ensure Discourse backups directory exists
  file: path={{ discourse_root }}/shared/standalone/backups/default/ owner=deploy group=deploy state=directory

- name: Add app configuration
  template: src=app.yml dest={{ discourse_root }}/containers/app.yml owner=deploy group=deploy

# launcher bootstrap needs a key pair at /root/.ssh/id_rsa otherwise it waits
- name: Ensure root .ssh directory exists
  file: path=/root/.ssh state=directory
- name: Generate root keypair
  command: ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' creates=/root/.ssh/id_rsa

- name: Bootstrap discourse app
  command: ./launcher bootstrap app chdir={{ discourse_root }} creates=/var/discourse/shared/standalone/log/rails/production.log
  notify: start discourse
