---
- name: Install nginx
  apt: pkg=nginx-light

- name: Ensure nginx is running
  service: name=nginx state=started enabled=true

- name: Generate the nginx config for the app
  template: src=discourse.nginx dest=/etc/nginx/sites-available/{{ discourse_server_name }} owner=root group=root mode=644
  notify: restart nginx

- name: Make the nginx site active
  file: state=link src=/etc/nginx/sites-available/{{ discourse_server_name }} dest=/etc/nginx/sites-enabled/{{ discourse_server_name }}
  notify: restart nginx
