---
- name: Download SSLMate APT source
  get_url:
    url: https://sslmate.com/apt/ubuntu1604/sslmate.list
    dest: /etc/apt/sources.list.d/sslmate.list

- name: Download SSLMate APT key
  get_url:
    url: https://sslmate.com/apt/ubuntu1604/sslmate.gpg
    dest: /etc/apt/trusted.gpg.d/sslmate.gpg

- name: Install SSLMate
  apt:
    name: sslmate
    update_cache: yes

- name: Copy SSLMate account configuration
  copy:
    src: sslmate.conf
    dest: /etc/sslmate.conf
    owner: root
    group: root
    mode: 0600

- name: Ensure that /etc/sslmate exists
  file:
    path: /etc/sslmate
    owner: root
    group: root
    state: directory

- name: Copy SSLMate morph.io key
  copy:
    src: morph.io.key
    dest: /etc/sslmate/morph.io.key
    owner: root
    group: root
    mode: 0600

- name: Download SSLMate certificates
  command: sslmate download morph.io creates=/etc/sslmate/morph.io.crt

- name: Create SSLMate automated renewals cronjob
  copy:
    src: sslmate_crontab
    dest: /etc/cron.daily/sslmate
    owner: root
    group: root
    mode: 0644
  when: cron_jobs

- name: Ensure /etc/nginx exists
  file: path=/etc/nginx owner=root group=root state=directory

- name: Copy across 2048-bit certificate for Diffie Hellman Ephemeral Paramerts
  copy: src=dhparam.pem dest=/etc/nginx/dhparam.pem

- name: Generate the overall nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
