---
- hosts: all
  become: root
  pre_tasks:
    - name: "Install aptitude, required by Ansible, missing in Ubuntu 16.04 LTS"
      raw: apt-get install python-minimal aptitude -y
      become: true
      become_user: root
      become_method: sudo
    - name: "Upgrade all packages"
      apt:
        update_cache: yes
        cache_valid_time: 300
        upgrade: yes
  roles:
    - discourse
